
services:
  turnero:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: turnero
    volumes:
      - .:/var/www/html
    networks:
      - redTurnero
    restart: always
    #QUITAR LOS PUERTOS Y LA DEPENDENCIA DE MARIADB
    ports:
      - "1234:80"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11.3
    container_name: mariadb_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - redTurnero

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - redTurnero
    depends_on:
      - mariadb

volumes:
  dbdata:

networks:
  redTurnero:
    driver: bridge
